USE VETERINARIA;

-- A) Qual a quantidade de animais registrados no sistema?
SELECT COUNT(*) AS ANIMAIS
FROM ANIMAL;

-- B) Qual o total de vacinas aplicadas registradas no sistema?
SELECT COUNT(*) AS VACINAS
FROM VACINA;

-- C) Quantos animais temos registrados para cada categoria?
SELECT TIPO_ANIMAL.NOME AS CATEGORIA, COUNT(ANIMAL.ID) AS TOTAL_ANIMAIS FROM ANIMAL
JOIN TIPO_ANIMAL ON ANIMAL.ID_TIPO_ANIMAL = TIPO_ANIMAL.ID
GROUP BY TIPO_ANIMAL.NOME;

-- D) Qual a categoria de animais que mais vacinas recebeu?
SELECT TIPO_ANIMAL.NOME AS CATERGORIA, COUNT(VACINA.ID) AS TOTAL_VACINAS FROM VACINA
JOIN ANIMAL ON VACINA.ID_ANIMAL = ANIMAL.ID
JOIN TIPO_ANIMAL ON ANIMAL.ID_TIPO_ANIMAL = TIPO_ANIMAL.ID
GROUP BY TIPO_ANIMAL.NOME
ORDER BY TOTAL_VACINAS DESC
LIMIT 1;