CREATE DATABASE Veterinaria;

USE Veterinaria;

CREATE TABLE TIPO_ANIMAL(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE ANIMAL(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    ID_TIPO_ANIMAL INT NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    COR VARCHAR(30),
    PESO FLOAT,
    ALTURA FLOAT,
    CONSTRAINT FK_ID_ANIMAL_ANIMAL
    FOREIGN KEY (ID_TIPO_ANIMAL)
    REFERENCES TIPO_ANIMAL (ID)
);

CREATE TABLE VACINA (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    DATA_APLICACAO DATE NOT NULL,
    ID_ANIMAL INT NOT NULL,
    CONSTRAINT FK_ID_ANIMAL_VACINA
    FOREIGN KEY (ID_ANIMAL)
    REFERENCES ANIMAL(ID)
);

CREATE INDEX IDX_ANIMAL_TIPO_ANIMAL
    ON ANIMAL (ID_TIPO_ANIMAL);

CREATE INDEX IDX_VACINA_ID_ANIMAL
    ON VACINA (ID_ANIMAL);

-- Inserção de Tipos de Animais
INSERT INTO TIPO_ANIMAL (NOME) VALUES ('CANINO');
INSERT INTO TIPO_ANIMAL (NOME) VALUES ('FELINO');
INSERT INTO TIPO_ANIMAL (NOME) VALUES ('SUÍNO');
INSERT INTO TIPO_ANIMAL (NOME) VALUES ('CAPRINO');
INSERT INTO TIPO_ANIMAL (NOME) VALUES ('EQUINO');

-- Inserção de Animais
INSERT INTO ANIMAL (NOME, ID_TIPO_ANIMAL, DT_NASCIMENTO, COR, PESO, ALTURA) 
VALUES ('Rex', 1, '2018-05-01', 'Marrom', 25.5, 0.8); 
INSERT INTO ANIMAL (NOME, ID_TIPO_ANIMAL, DT_NASCIMENTO, COR, PESO, ALTURA) 
VALUES ('Miau', 2, '2019-08-15', 'Preto', 4.2, 0.4); 

-- Inserção de Vacinas
INSERT INTO VACINA (NOME, DATA_APLICACAO, ID_ANIMAL) 
VALUES ('Vacina Antirrábica', '2023-06-15', 1); 
INSERT INTO VACINA (NOME, DATA_APLICACAO, ID_ANIMAL) 
VALUES ('Vacina V8', '2023-07-20', 1); 
INSERT INTO VACINA (NOME, DATA_APLICACAO, ID_ANIMAL) 
VALUES ('Vacina Felina', '2023-09-05', 2);


UPDATE ANIMAL
SET COR = 'Branco', PESO = 26, ALTURA = 0.9
WHERE ID = 1;


INSERT INTO ANIMAL (NOME, ID_TIPO_ANIMAL, DT_NASCIMENTO, COR, PESO, ALTURA) VALUES ('Snoopy', '1', '2017-02-01', 'Preto', 3.5, 0.3);

SELECT * FROM ANIMAL

DELETE FROM ANIMAL WHERE ID = 3;

